2022-12-05 11:13:18,435 INFO    MainThread:2300 [wandb_setup.py:_flush():68] Configure stats pid to 2300
2022-12-05 11:13:18,435 INFO    MainThread:2300 [wandb_setup.py:_flush():68] Loading settings from C:\Users\User\.config\wandb\settings
2022-12-05 11:13:18,435 INFO    MainThread:2300 [wandb_setup.py:_flush():68] Loading settings from c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\settings
2022-12-05 11:13:18,435 INFO    MainThread:2300 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-12-05 11:13:18,435 INFO    MainThread:2300 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-12-05 11:13:18,435 INFO    MainThread:2300 [wandb_init.py:_log_setup():476] Logging user logs to c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\run-20221205_111318-190nph9h\logs\debug.log
2022-12-05 11:13:18,436 INFO    MainThread:2300 [wandb_init.py:_log_setup():477] Logging internal logs to c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\run-20221205_111318-190nph9h\logs\debug-internal.log
2022-12-05 11:13:18,436 INFO    MainThread:2300 [wandb_init.py:init():516] calling init triggers
2022-12-05 11:13:18,436 INFO    MainThread:2300 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-05, 'epochs': 8000, 'batch_size': 10, 'dataset': ['tree0.dat', 'tree1.dat', 'tree10.dat', 'tree100.dat', 'tree101.dat', 'tree102.dat', 'tree103.dat', 'tree104.dat', 'tree105.dat', 'tree106.dat', 'tree107.dat', 'tree108.dat', 'tree109.dat', 'tree11.dat', 'tree110.dat', 'tree111.dat', 'tree112.dat', 'tree113.dat', 'tree114.dat', 'tree115.dat'], 'number of trees': 20, 'optim': Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 1e-05
    maximize: False
    weight_decay: 0
)}
2022-12-05 11:13:18,436 INFO    MainThread:2300 [wandb_init.py:init():535] re-initializing run, found existing run on stack: m3zrnzpg
2022-12-05 11:13:18,438 INFO    MainThread:2300 [wandb_run.py:_finish():1746] finishing run paufeldman/autoencoder4/m3zrnzpg
2022-12-05 11:13:18,438 INFO    MainThread:2300 [jupyter.py:save_history():448] not saving jupyter history
2022-12-05 11:13:18,438 INFO    MainThread:2300 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-12-05 11:13:18,438 INFO    MainThread:2300 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2022-12-05 11:13:18,438 INFO    MainThread:2300 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-12-05 11:13:18,438 INFO    MainThread:2300 [wandb_run.py:_restore():1932] restore
2022-12-05 11:13:18,439 INFO    MainThread:2300 [wandb_run.py:_restore():1938] restore done
2022-12-05 11:14:01,668 INFO    MainThread:2300 [wandb_init.py:init():569] starting backend
2022-12-05 11:14:01,668 INFO    MainThread:2300 [wandb_init.py:init():573] setting up manager
2022-12-05 11:14:01,678 INFO    MainThread:2300 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-12-05 11:14:01,682 INFO    MainThread:2300 [wandb_init.py:init():580] backend started and connected
2022-12-05 11:14:01,695 INFO    MainThread:2300 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2022-12-05 11:14:01,695 INFO    MainThread:2300 [wandb_run.py:_label_probe_notebook():1123] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-12-05 11:14:01,695 INFO    MainThread:2300 [wandb_init.py:init():658] updated telemetry
2022-12-05 11:14:01,730 INFO    MainThread:2300 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
