2022-11-23 17:27:44,184 INFO    MainThread:2148 [wandb_setup.py:_flush():68] Configure stats pid to 2148
2022-11-23 17:27:44,184 INFO    MainThread:2148 [wandb_setup.py:_flush():68] Loading settings from C:\Users\User\.config\wandb\settings
2022-11-23 17:27:44,185 INFO    MainThread:2148 [wandb_setup.py:_flush():68] Loading settings from c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\settings
2022-11-23 17:27:44,185 INFO    MainThread:2148 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-23 17:27:44,185 INFO    MainThread:2148 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-11-23 17:27:44,185 INFO    MainThread:2148 [wandb_init.py:_log_setup():476] Logging user logs to c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\run-20221123_172744-3nf357hm\logs\debug.log
2022-11-23 17:27:44,186 INFO    MainThread:2148 [wandb_init.py:_log_setup():477] Logging internal logs to c:\Users\User\Documents\rpoditela\Intra\autoencoder\wandb\run-20221123_172744-3nf357hm\logs\debug-internal.log
2022-11-23 17:27:44,186 INFO    MainThread:2148 [wandb_init.py:init():516] calling init triggers
2022-11-23 17:27:44,186 INFO    MainThread:2148 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0001, 'epochs': 8000, 'batch_size': 1, 'dataset': ['ArteryObjAN1-17-nl.dat'], 'number of trees': 1, 'optim': Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.0001
    maximize: False
    weight_decay: 0
)}
2022-11-23 17:27:44,186 INFO    MainThread:2148 [wandb_init.py:init():535] re-initializing run, found existing run on stack: 36t9vgpb
2022-11-23 17:27:44,188 INFO    MainThread:2148 [wandb_run.py:_finish():1746] finishing run paufeldman/autoencoder3/36t9vgpb
2022-11-23 17:27:44,258 INFO    MainThread:2148 [jupyter.py:save_history():448] not saving jupyter history
2022-11-23 17:27:44,259 INFO    MainThread:2148 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2022-11-23 17:27:44,259 INFO    MainThread:2148 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2022-11-23 17:27:44,259 INFO    MainThread:2148 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2022-11-23 17:27:44,259 INFO    MainThread:2148 [wandb_run.py:_restore():1932] restore
2022-11-23 17:27:44,259 INFO    MainThread:2148 [wandb_run.py:_restore():1938] restore done
